production:
  solr:
    hostname: node-2.hosted-solr.com
    port: 443
    log_level: WARNING
    path: /667f7c93eae-cholon-solr/core
    user: <%= ENV["SOLR_USER"] %>
    password: <%= ENV["SOLR_PASSWORD"] %>
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    